language: go

sudo: required

notifications:
  email: false

env:
  global:
    - H2O_VERSION=1.6.3
    - PROJECT_ROOT=$HOME/gopath/src/github.com/kayac/Gunfish

go:
  - 1.7.4
  - 1.8

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

install:
  - cd $PROJECT_ROOT && ./test/scripts/build_h2o.sh
  - cd $PROJECT_ROOT && make get-deps
  - go get github.com/mitchellh/gox

script:
  - make test

before_deploy:
  - cd $PROJECT_ROOT && make packages

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - pkg/*.{zip}
  on:
    tags: true
    go: 1.7.4

cache:
  directories:
    - $PROJECT_ROOT/h2o-$H2O_VERSION
